In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
test_df = pd.read_csv("data/train/train_data.csv", index_col=False)
test_df

         time  x-acceleration  y-acceleration  z-acceleration   output
0        0.00           0.577           0.532           0.598     drum
1        0.02           0.587           0.539           0.600     drum
2        0.04           0.590           0.537           0.595     drum
3        0.06           0.589           0.533           0.591     drum
4        0.08           0.584           0.534           0.590     drum
...       ...             ...             ...             ...      ...
21844  436.88           0.750           0.522           0.394  unknown
21845  436.90           0.747           0.520           0.391  unknown
21846  436.92           0.748           0.520           0.397  unknown
21847  436.94           0.753           0.523           0.397  unknown
21848  436.96           0.752           0.523           0.395  unknown

[21849 rows x 5 columns]